version: '3'
services:
  platform:
    image: bootx-platform:latest
    restart: always
    ports:
      - "8080:8080"
    volumes:
      # 宿主机目录:容器目录 日志映射
      - /data/logs/bootx-platform:/logs
      # 外部化配置文件
      - ./application.yml:/application.yml
      - ./logback-spring.xml:/logback-spring.xml
