server:
  port: 9999
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password : ${REDIS_PASSWORD}
    database: ${REDIS_DATABASE}
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port:  ${RABBITMQ_PORT}
    username:  ${RABBITMQ_USERNAME}
    password:  ${RABBITMQ_PASSWORD}
    listener:
      simple:
        # 重试机制
        retry:
          enabled: true
          max-attempts: 5
  data:
    mongodb:
      host: ${MONGODB_HOST}
      database: ${MONGODB_DATABASE}
      port: ${MONGODB_PORT}
      username: ${MONGODB_USERNAME}
      password: ${MONGODB_PASSWORD}
  #静态资源加载配置
  mvc:
    static-path-pattern: /**
  web:
    resources:
      static-locations: classpath:/static/,classpath:/public/
  # 数据库版本管理
  flyway:
    # 如果 flyway_schema_history 不存在自动创建
    baseline-on-migrate: true
    # 开发模式开启
    enabled: true
  # 定时任务
  quartz:
    # 持久化方式
    job-store-type: jdbc
    #定时任务启动开关，true-开  false-关
    auto-startup: true
    #启动时更新己存在的Job
    overwrite-existing-jobs: true
    properties:
      org:
        quartz:
          scheduler:
            instanceName: quartzScheduler
            instanceId: AUTO
          threadPool:
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
# 项目配置
bootx:
  common:
    # 接口文档
    swagger:
      enabled: false
    # 缓存
    cache:
      keys-ttl:
        "[iam:user:path]" : 5200
        "[iam:ignore:path]" : 5200
    # 序列生成器
    sequence:
      type: jdbc
  starter:
    auth:
      default-password: 123456
      ignore-urls:
        - '/actuator/**'
        - '/v3/api-docs/**'
        - '/doc.html'
        - '/swagger-resources/**'
        - '/token/**'
        - '/webjars/**'
        - '/css/**'
        - '/favicon.ico'
        - '/error'
    # 审计日志存储
    audit-log:
      store: mongo
    # 文件上传
    file-upload:
      upload-type: mongo
      mongo:
        bucket: fs
    # 数据权限
    data-perm:
      fieldDecryptKey: "UCrtxSCwYZNCIlav"
